//
// ECGraphPoint.m
//
// Create By ECGenerateCode
// Date:2010-05-06 18:44:34
//
//!--
//This is generated by code generater automatic,pls check the type of variables.
//Change them to other suitable type(NSString is by default) if needed.
//--

#import "ECGraphPoint.h"

@implementation ECGraphPoint

@synthesize xValue;
@synthesize yValue;
@synthesize data;
@synthesize xDateValue;
@synthesize yDateValue;

- (id)init{
	if(self = [super init]){
		xValue = 0;
		yValue = 0;
		data = @"";
		xDateValue = nil;
		yDateValue = nil;
	}
	return self;
}

- (void)dealloc{
	[xDateValue release];
	[yDateValue release];
	[data release];
	[super dealloc];
}

@end