//
// ECGraphPoint.h
//
// Create By ECGenerateCode
// Date:2010-05-06 18:44:34
//
//!--
//This is generated by code generater automatic,pls check the type of variables.
//Change them to other suitable type(NSString is by default) if needed.
//--

#import <Foundation/Foundation.h>

@interface ECGraphPoint : NSObject {
	NSDate		*xDateValue;
	NSDate		*yDateValue;
	int			xValue;
	int			yValue;
	NSString	*data;
}

@property(nonatomic,assign) int xValue;
@property(nonatomic,assign) int yValue;
@property(nonatomic,retain) NSDate *xDateValue;
@property(nonatomic,retain) NSDate *yDateValue;
@property(nonatomic,retain) NSString *data;

@end